name: Build to Heroku Docker image.

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKO_API_TOKEN }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKO_API_TOKEN }}
        run: heroku container:push -a productify-me web 
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKO_API_TOKEN }}
        run: heroku container:release -a productify-me web 

      