name: Build to Heroku Docker image.

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-action@v1
        with:
          repository: registry.heroku.com/productify-me/web
          tags: latest
      - name: Login to Heroku
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{secrets.HEROKO_API_TOKEN}}
      - name: push
        uses: docker/push-action@v1
        with:
          registry: registry.heroku.com
          tags: latest